let data = {
  Animals: "/images/animal.png",
  Art: "/images/art.png",
  "Entertainment: Books": "/images/books.png",
  Vehicles: "/images/car.png",
  "Entertainment: Cartoon & Animations": "/images/cartoon.png",
  Celebrities: "/images/celeb.png",
  "Entertainment: Board Games": "/images/chess.png",
  "Entertainment: Comics": "/images/comics.png",
  "Entertainment: Japanese Anime & Manga": "/images/eren.png",
  "Entertainment: Film": "/images/film.png",
  "Science: Gadgets": "/images/gadgets.png",
  "Entertainment: Video Games": "/images/game.png",
  Geography: "/images/geography.png",
  "General Knowledge": "/images/gk.png",
  Mythology: "/images/greek.png",
  History: "/images/history.png",
  "Science: Mathematics": "/images/maths.png",
  "Entertainment: Music": "/images/music.png",
  "Science: Computers": "/images/pc.png",
  Politics: "/images/politics.png",
  "Science & Nature": "/images/science.png",
  Sports: "/images/sports.png",
  "Entertainment: Musicals & Theatres": "/images/theatre.png",
  "Entertainment: Television": "/images/tv.png",
};

// let categories = [
//   { id: 9, name: "General Knowledge" },
//   { id: 10, name: "Entertainment: Books" },
//   { id: 11, name: "Entertainment: Film" },
//   { id: 12, name: "Entertainment: Music" },
//   { id: 13, name: "Entertainment: Musicals & Theatres" },
//   { id: 14, name: "Entertainment: Television" },
//   { id: 15, name: "Entertainment: Video Games" },
//   { id: 16, name: "Entertainment: Board Games" },
//   { id: 17, name: "Science & Nature" },
//   { id: 18, name: "Science: Computers" },
//   { id: 19, name: "Science: Mathematics" },
//   { id: 20, name: "Mythology" },
//   { id: 21, name: "Sports" },
//   { id: 22, name: "Geography" },
//   { id: 23, name: "History" },
//   { id: 24, name: "Politics" },
//   { id: 25, name: "Art" },
//   { id: 26, name: "Celebrities" },
//   { id: 27, name: "Animals" },
//   { id: 28, name: "Vehicles" },
//   { id: 29, name: "Entertainment: Comics" },
//   { id: 30, name: "Science: Gadgets" },
//   { id: 31, name: "Entertainment: Japanese Anime & Manga" },
//   { id: 32, name: "Entertainment: Cartoon & Animations" },
// ];

export default data;
