let data = {
  Animals: "/images/animal.png",
  Art: "/images/art.png",
  "Entertainment: Books": "/images/books.png",
  Vehicles: "/images/car.png",
  "Entertainment: Cartoon & Animations": "/images/cartoon.png",
  Celebrities: "/images/celeb.png",
  "Entertainment: Board Games": "/images/chess.png",
  "Entertainment: Comics": "/images/comics.png",
  "Entertainment: Japanese Anime & Manga": "/images/eren.png",
  "Entertainment: Film": "/images/film.png",
  "Science: Gadgets": "/images/gadgets.png",
  "Entertainment: Video Games": "/images/game.png",
  Geography: "/images/geography.png",
  "General Knowledge": "/images/gk.png",
  Mythology: "/images/greek.png",
  History: "/images/history.png",
  "Science: Mathematics": "/images/maths.png",
  "Entertainment: Music": "/images/music.png",
  "Science: Computers": "/images/pc.png",
  Politics: "/images/politics.png",
  "Science & Nature": "/images/science.png",
  Sports: "/images/sports.png",
  "Entertainment: Musicals & Theatres": "/images/theatre.png",
  "Entertainment: Television": "/images/tv.png",
};
export default data;
